### ISSUE TITLE
build for ios fails with errors

### ISSUE THREAD

**Issue by Rubytastic2** [rajayogan/ionic2-authentication#1]
Any thought on how to resolve below issues?

```
[20:16:06]  Error: Error at /srv/.tmp/pages/userpage/userpage.ts:28:15
[20:16:06]  Property 'success' does not exist on type '{}'.
[20:16:06]  Error at /srv/.tmp/pages/userpage/userpage.ts:30:23
[20:16:06]  Property 'success' does not exist on type '{}'.
[20:16:06]  Error at /srv/.tmp/pages/userpage/userpage.ts:31:26
[20:16:06]  Property 'msg' does not exist on type '{}'.
[20:16:06]  ngc failed
[20:16:06]  ionic-app-script task: "build"
[20:16:06]  Error: Error
```

Im using rc-1 ionic2 and have just started with ionic and angular. 
It seems

**Comment by Rubytastic2** [comment]
Also

```
20:36:56]  tslint: src/pages/home/authservice.ts, line: 1
            Unused import: 'Inject'

       L1:  import {Injectable, Inject} from '@angular/core';
       L2:  import {Http, Headers} from '@angular/http';

[20:36:56]  lint finished in 1.54 s
[20:36:57]  typescript: src/pages/userpage/userpage.ts, line: 28
            Property 'success' does not exist on type '{}'.

      L27:  this.authservice.getinfo().then(data => {
      L28:    if(data.success) {
      L29:      var alert = this.alertCtrl.create({

[20:36:57]  typescript: src/pages/userpage/userpage.ts, line: 30
            Property 'success' does not exist on type '{}'.

      L29:  var alert = this.alertCtrl.create({
      L30:    title: data.success,
      L31:    subTitle: data.msg,

[20:36:57]  typescript: src/pages/userpage/userpage.ts, line: 31
            Property 'msg' does not exist on type '{}'.

      L30:  title: data.success,
      L31:  subTitle: data.msg,
      L32:  buttons: ['ok']

[20:36:57]  transpile failed
```

I have the backend setup and running

**Comment by samsagaz** [comment]
having the same error.

**Comment by samsagaz** [comment]
replace line 20 of userpage.ts to this.authservice.getinfo().then((data : any) => {

and will be fixed
